package com.inmarsat.profitcentre;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ESASRequest implements java.io.Serializable
{

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String hardwareId;
	private String imnId;
	private String terminalId;
	private String countryOfRegistration;
	private String catCode;
	private String imoNo;
	private String vesselName;
	private String aesType;
	private String aesModel;
	private String tailNo;
	private String callSign;
	private String mmsi;
	private String standardId;
	private String antennaId;
	private String mesCategoryCode;
	private String aeroServiceType;
	private String ownerCode;
	private String profitCentre;
	private String businessUnit;
	private String commVerticalMarket;
	private String scapId;
	private String product;
	private String subscriber;
	private String ratePlan;
	private String verticalMarket;
	private String simcardId;
	private String countryName;
	private String marketSector;
	private String imoNumber;
	private String typeOfVessel;
	private String aircraftModel;
	private String aeroType;
	private String effectiveDate;
	private String idType;
	private String organisaionId;
	private String organisationName;	
	private String verticalMarketKey;	
	private String customerKey;	
	private String customerName;	
	private String companyName;	
	private String companyId;
	private String productCode;
	private String dpId;
	private String satisfiedRuleName;
	private String businessUnitPC;
	private String createdBy;
	private String updatedBy;
	private Date createdTime;
	private Date updatedTime;
	private String terminalType;
	private String status;
	private String sourceSystem;

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getImnId() {
		return imnId;
	}
	public void setImnId(String imnId) {
		this.imnId = imnId;
	}
	public String getTerminalId() {
		return terminalId;
	}
	public void setTerminalId(String terminalId) {
		this.terminalId = terminalId;
	}
	public String getCountryOfRegistration() {
		return countryOfRegistration;
	}
	public void setCountryOfRegistration(String countryOfRegistration) {
		this.countryOfRegistration = countryOfRegistration;
	}
	public String getCatCode() {
		return catCode;
	}
	public void setCatCode(String catCode) {
		this.catCode = catCode;
	}
	public String getImoNo() {
		return imoNo;
	}
	public void setImoNo(String imoNo) {
		this.imoNo = imoNo;
	}
	public String getVesselName() {
		return vesselName;
	}
	public void setVesselName(String vesselName) {
		this.vesselName = vesselName;
	}
	public String getAesType() {
		return aesType;
	}
	public void setAesType(String aesType) {
		this.aesType = aesType;
	}
	public String getAesModel() {
		return aesModel;
	}
	public void setAesModel(String aesModel) {
		this.aesModel = aesModel;
	}
	public String getTailNo() {
		return tailNo;
	}
	public void setTailNo(String tailNo) {
		this.tailNo = tailNo;
	}
	public String getCallSign() {
		return callSign;
	}
	public void setCallSign(String callSign) {
		this.callSign = callSign;
	}
	public String getMmsi() {
		return mmsi;
	}
	public void setMmsi(String mmsi) {
		this.mmsi = mmsi;
	}
	public String getStandardId() {
		return standardId;
	}
	public void setStandardId(String standardId) {
		this.standardId = standardId;
	}
	public String getAntennaId() {
		return antennaId;
	}
	public void setAntennaId(String antennaId) {
		this.antennaId = antennaId;
	}
	public String getMesCategoryCode() {
		return mesCategoryCode;
	}
	public void setMesCategoryCode(String mesCategoryCode) {
		this.mesCategoryCode = mesCategoryCode;
	}
	public String getAeroServiceType() {
		return aeroServiceType;
	}
	public void setAeroServiceType(String aeroServiceType) {
		this.aeroServiceType = aeroServiceType;
	}
	public String getOwnerCode() {
		return ownerCode;
	}
	public void setOwnerCode(String ownerCode) {
		this.ownerCode = ownerCode;
	}

	public String getProfitCentre() {
		return profitCentre;
	}
	public void setProfitCentre(String profitCentre) {
		this.profitCentre = profitCentre;
	}
	public String getBusinessUnit() {
		return businessUnit;
	}
	public void setBusinessUnit(String businessUnit) {
		this.businessUnit = businessUnit;
	}
	public String getCommVerticalMarket() {
		return commVerticalMarket;
	}
	public void setCommVerticalMarket(String commVerticalMarket) {
		this.commVerticalMarket = commVerticalMarket;
	}
	public String getScapId() {
		return scapId;
	}
	public void setScapId(String scapId) {
		this.scapId = scapId;
	}
	public String getProduct() {
		return product;
	}
	public void setProduct(String product) {
		this.product = product;
	}
	public String getSubscriber() {
		return subscriber;
	}
	public void setSubscriber(String subscriber) {
		this.subscriber = subscriber;
	}
	public String getRatePlan() {
		return ratePlan;
	}
	public void setRatePlan(String ratePlan) {
		this.ratePlan = ratePlan;
	}
	public String getVerticalMarket() {
		return verticalMarket;
	}
	public void setVerticalMarket(String verticalMarket) {
		this.verticalMarket = verticalMarket;
	}
	public String getSimcardId() {
		return simcardId;
	}
	public void setSimcardId(String simcardId) {
		this.simcardId = simcardId;
	}
	public String getCountryName() {
		return countryName;
	}
	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}
	public String getMarketSector() {
		return marketSector;
	}
	public void setMarketSector(String marketSector) {
		this.marketSector = marketSector;
	}
	public String getImoNumber() {
		return imoNumber;
	}
	public void setImoNumber(String imoNumber) {
		this.imoNumber = imoNumber;
	}
	public String getTypeOfVessel() {
		return typeOfVessel;
	}
	public void setTypeOfVessel(String typeOfVessel) {
		this.typeOfVessel = typeOfVessel;
	}
	public String getAircraftModel() {
		return aircraftModel;
	}
	public void setAircraftModel(String aircraftModel) {
		this.aircraftModel = aircraftModel;
	}
	public String getAeroType() {
		return aeroType;
	}
	public void setAeroType(String aeroType) {
		this.aeroType = aeroType;
	}
	public String getEffectiveDate() {
		return effectiveDate;
	}
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	public String getIdType() {
		return idType;
	}
	public void setIdType(String idType) {
		this.idType = idType;
	}
	public String getOrganisaionId() {
		return organisaionId;
	}
	public void setOrganisaionId(String organisaionId) {
		this.organisaionId = organisaionId;
	}
	public String getOrganisationName() {
		return organisationName;
	}
	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}
	public String getVerticalMarketKey() {
		return verticalMarketKey;
	}
	public void setVerticalMarketKey(String verticalMarketKey) {
		this.verticalMarketKey = verticalMarketKey;
	}
	public String getCustomerKey() {
		return customerKey;
	}
	public void setCustomerKey(String customerKey) {
		this.customerKey = customerKey;
	}
	public String getCustomerName() {
		return customerName;
	}
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getCompanyId() {
		return companyId;
	}
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}
	public String getProductCode() {
		return productCode;
	}
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}
	public String getDpId() {
		return dpId;
	}
	public void setDpId(String dpId) {
		this.dpId = dpId;
	}
	public String getSatisfiedRuleName() {
		return satisfiedRuleName;
	}
	public void setSatisfiedRuleName(String satisfiedRuleName) {
		this.satisfiedRuleName = satisfiedRuleName;
	}
	public String getBusinessUnitPC() {
		return businessUnitPC;
	}
	public void setBusinessUnitPC(String businessUnitPC) {
		this.businessUnitPC = businessUnitPC;
	}
	public String getHardwareId() {
		return hardwareId;
	}
	public void setHardwareId(String hardwareId) {
		this.hardwareId = hardwareId;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getUpdatedBy() {
		return updatedBy;
	}
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	public Date getCreatedTime() {
		return createdTime;
	}
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}
	public Date getUpdatedTime() {
		return updatedTime;
	}
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
	public String getTerminalType() {
		return terminalType;
	}
	public void setTerminalType(String terminalType) {
		this.terminalType = terminalType;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getSourceSystem() {
		return sourceSystem;
	}
	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}
	@Override
	public String toString() {
		return "ESASRequest [id=" + id + ", hardwareId=" + hardwareId + ", imnId=" + imnId + ", terminalId="
				+ terminalId + ", countryOfRegistration=" + countryOfRegistration + ", catCode=" + catCode + ", imoNo="
				+ imoNo + ", vesselName=" + vesselName + ", aesType=" + aesType + ", aesModel=" + aesModel + ", tailNo="
				+ tailNo + ", callSign=" + callSign + ", mmsi=" + mmsi + ", standardId=" + standardId + ", antennaId="
				+ antennaId + ", mesCategoryCode=" + mesCategoryCode + ", aeroServiceType=" + aeroServiceType
				+ ", ownerCode=" + ownerCode + ", profitCentre=" + profitCentre + ", businessUnit=" + businessUnit
				+ ", commVerticalMarket=" + commVerticalMarket + ", scapId=" + scapId + ", product=" + product
				+ ", subscriber=" + subscriber + ", ratePlan=" + ratePlan + ", verticalMarket=" + verticalMarket
				+ ", simcardId=" + simcardId + ", countryName=" + countryName + ", marketSector=" + marketSector
				+ ", imoNumber=" + imoNumber + ", typeOfVessel=" + typeOfVessel + ", aircraftModel=" + aircraftModel
				+ ", aeroType=" + aeroType + ", effectiveDate=" + effectiveDate + ", idType=" + idType
				+ ", organisaionId=" + organisaionId + ", organisationName=" + organisationName + ", verticalMarketKey="
				+ verticalMarketKey + ", customerKey=" + customerKey + ", customerName=" + customerName
				+ ", companyName=" + companyName + ", companyId=" + companyId + ", productCode=" + productCode
				+ ", dpId=" + dpId + ", satisfiedRuleName=" + satisfiedRuleName + ", businessUnitPC=" + businessUnitPC
				+ ", createdBy=" + createdBy + ", updatedBy=" + updatedBy + ", createdTime=" + createdTime
				+ ", updatedTime=" + updatedTime + ", terminalType=" + terminalType + ", status=" + status
				+ ", sourceSystem=" + sourceSystem + "]";
	}
}