package com.inmarsat.profitcentre;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceOrder implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private Long id;
	private String msisdn;
	private String industryCode;
	private String profitCenter;
	private String requestId;
	private String productCode;
	private String satisfiedRuleName;
	private boolean isManualValidationRequired;
	private boolean isManualSegmentationRequired;
	private String salesRegion;
	private String salesRegionCode;
	private String dpName;
	private String billingProfileCode;
	private String arAccountCode;
	private String prevBusinessUnit;
	private String prevCommericialMarket;
	private String prevRuleId;
	private String grpPkgInstance;
	private String wholeSaleCust;
	private String castOrgName;
	private String castVerticalMarket;
	private String createdBy;
	private String updatedBy;
	private Date createdTime;
	private Date updatedTime;
	private String dpId;
	private String businessUnit;
	private String commVerticalMarket;
	private String scapId;
	private String product;
	private String subscriber;
	private String ratePlan;
	private String verticalMarket;
	private String simcardId;

	private String countryName;
	private String marketSector;
	private String imoNumber;
	private String vesselName;
	private String typeOfVessel;
	private String aircraftModel;
	private String aeroType;
	private String tailNo;
	private String callSign;
	private String effectiveDate;
	private String mmsi;
	private String idType;
	private String organisaionId;
	private String organisationName;
	private String verticalMarketKey;
	private String customerKey;
	private String customerName;
	private String companyId;
	private String companyName;
	private String hardwareId;
	private String imsiNumber;
	private String corporateName;
	private String prevCommCustomer;
	private String groupPackageInstanceId;
	private String vesselType;
	private String aircraftClass; 
	private String aircraftManufacturer;
	private String tailNumber;
	private String countryOfRegistration;
	private String status;
	private String ratePlanId;
	private boolean ratePlanChangeInd;
	private String suffix;
	private String salesOrg;
	private String sourceSyatem;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getMsisdn() {
		return msisdn;
	}
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}
	public String getIndustryCode() {
		return industryCode;
	}
	public void setIndustryCode(String industryCode) {
		this.industryCode = industryCode;
	}
	public String getProfitCenter() {
		return profitCenter;
	}
	public void setProfitCenter(String profitCenter) {
		this.profitCenter = profitCenter;
	}
	public String getRequestId() {
		return requestId;
	}
	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}
	public String getProductCode() {
		return productCode;
	}
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getSatisfiedRuleName() {
		return satisfiedRuleName;
	}
	public void setSatisfiedRuleName(String satisfiedRuleName) {
		this.satisfiedRuleName = satisfiedRuleName;
	}
	public boolean isManualValidationRequired() {
		return isManualValidationRequired;
	}
	public void setManualValidationRequired(boolean isManualValidationRequired) {
		this.isManualValidationRequired = isManualValidationRequired;
	}
	public boolean isManualSegmentationRequired() {
		return isManualSegmentationRequired;
	}
	public void setManualSegmentationRequired(boolean isManualSegmentationRequired) {
		this.isManualSegmentationRequired = isManualSegmentationRequired;
	}
	public String getSalesRegion() {
		return salesRegion;
	}
	public void setSalesRegion(String salesRegion) {
		this.salesRegion = salesRegion;
	}
	public String getSalesRegionCode() {
		return salesRegionCode;
	}
	public void setSalesRegionCode(String salesRegionCode) {
		this.salesRegionCode = salesRegionCode;
	}
	public String getDpName() {
		return dpName;
	}
	public void setDpName(String dpName) {
		this.dpName = dpName;
	}
	public String getBillingProfileCode() {
		return billingProfileCode;
	}
	public void setBillingProfileCode(String billingProfileCode) {
		this.billingProfileCode = billingProfileCode;
	}
	public String getArAccountCode() {
		return arAccountCode;
	}
	public void setArAccountCode(String arAccountCode) {
		this.arAccountCode = arAccountCode;
	}
	public String getPrevBusinessUnit() {
		return prevBusinessUnit;
	}
	public void setPrevBusinessUnit(String prevBusinessUnit) {
		this.prevBusinessUnit = prevBusinessUnit;
	}
	public String getPrevCommericialMarket() {
		return prevCommericialMarket;
	}
	public void setPrevCommericialMarket(String prevCommericialMarket) {
		this.prevCommericialMarket = prevCommericialMarket;
	}
	public String getPrevRuleId() {
		return prevRuleId;
	}
	public void setPrevRuleId(String prevRuleId) {
		this.prevRuleId = prevRuleId;
	}
	public String getGrpPkgInstance() {
		return grpPkgInstance;
	}
	public void setGrpPkgInstance(String grpPkgInstance) {
		this.grpPkgInstance = grpPkgInstance;
	}
	public String getWholeSaleCust() {
		return wholeSaleCust;
	}
	public void setWholeSaleCust(String wholeSaleCust) {
		this.wholeSaleCust = wholeSaleCust;
	}
	public String getCastOrgName() {
		return castOrgName;
	}
	public void setCastOrgName(String castOrgName) {
		this.castOrgName = castOrgName;
	}
	public String getCastVerticalMarket() {
		return castVerticalMarket;
	}
	public void setCastVerticalMarket(String castVerticalMarket) {
		this.castVerticalMarket = castVerticalMarket;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getUpdatedBy() {
		return updatedBy;
	}
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	public Date getCreatedTime() {
		return createdTime;
	}
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}
	public Date getUpdatedTime() {
		return updatedTime;
	}
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
	public String getDpId() {
		return dpId;
	}
	public void setDpId(String dpId) {
		this.dpId = dpId;
	}
	public String getBusinessUnit() {
		return businessUnit;
	}
	public void setBusinessUnit(String businessUnit) {
		this.businessUnit = businessUnit;
	}
	public String getCommVerticalMarket() {
		return commVerticalMarket;
	}
	public void setCommVerticalMarket(String commVerticalMarket) {
		this.commVerticalMarket = commVerticalMarket;
	}
	public String getScapId() {
		return scapId;
	}
	public void setScapId(String scapId) {
		this.scapId = scapId;
	}
	public String getProduct() {
		return product;
	}
	public void setProduct(String product) {
		this.product = product;
	}
	public String getSubscriber() {
		return subscriber;
	}
	public void setSubscriber(String subscriber) {
		this.subscriber = subscriber;
	}
	public String getRatePlan() {
		return ratePlan;
	}
	public void setRatePlan(String ratePlan) {
		this.ratePlan = ratePlan;
	}
	public String getVerticalMarket() {
		return verticalMarket;
	}
	public void setVerticalMarket(String verticalMarket) {
		this.verticalMarket = verticalMarket;
	}
	public String getSimcardId() {
		return simcardId;
	}
	public void setSimcardId(String simcardId) {
		this.simcardId = simcardId;
	}

	public String getCountryName() {
		return countryName;
	}
	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}
	public String getMarketSector() {
		return marketSector;
	}
	public void setMarketSector(String marketSector) {
		this.marketSector = marketSector;
	}
	public String getImoNumber() {
		return imoNumber;
	}
	public void setImoNumber(String imoNumber) {
		this.imoNumber = imoNumber;
	}
	public String getVesselName() {
		return vesselName;
	}
	public void setVesselName(String vesselName) {
		this.vesselName = vesselName;
	}
	public String getTypeOfVessel() {
		return typeOfVessel;
	}
	public void setTypeOfVessel(String typeOfVessel) {
		this.typeOfVessel = typeOfVessel;
	}
	public String getAircraftModel() {
		return aircraftModel;
	}
	public void setAircraftModel(String aircraftModel) {
		this.aircraftModel = aircraftModel;
	}
	public String getAeroType() {
		return aeroType;
	}
	public void setAeroType(String aeroType) {
		this.aeroType = aeroType;
	}
	public String getTailNo() {
		return tailNo;
	}
	public void setTailNo(String tailNo) {
		this.tailNo = tailNo;
	}
	public String getCallSign() {
		return callSign;
	}
	public void setCallSign(String callSign) {
		this.callSign = callSign;
	}
	public String getEffectiveDate() {
		return effectiveDate;
	}
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}
	public String getMmsi() {
		return mmsi;
	}
	public void setMmsi(String mmsi) {
		this.mmsi = mmsi;
	}
	public String getIdType() {
		return idType;
	}
	public void setIdType(String idType) {
		this.idType = idType;
	}
	public String getOrganisaionId() {
		return organisaionId;
	}
	public void setOrganisaionId(String organisaionId) {
		this.organisaionId = organisaionId;
	}
	public String getOrganisationName() {
		return organisationName;
	}
	public void setOrganisationName(String organisationName) {
		this.organisationName = organisationName;
	}
	public String getVerticalMarketKey() {
		return verticalMarketKey;
	}
	public void setVerticalMarketKey(String verticalMarketKey) {
		this.verticalMarketKey = verticalMarketKey;
	}
	public String getCustomerKey() {
		return customerKey;
	}
	public void setCustomerKey(String customerKey) {
		this.customerKey = customerKey;
	}
	public String getCustomerName() {
		return customerName;
	}
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	public String getCompanyId() {
		return companyId;
	}
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getHardwareId() {
		return hardwareId;
	}
	public void setHardwareId(String hardwareId) {
		this.hardwareId = hardwareId;
	}
	public String getImsiNumber() {
		return imsiNumber;
	}
	public void setImsiNumber(String imsiNumber) {
		this.imsiNumber = imsiNumber;
	}
	public String getCorporateName() {
		return corporateName;
	}
	public void setCorporateName(String corporateName) {
		this.corporateName = corporateName;
	}
	public String getPrevCommCustomer() {
		return prevCommCustomer;
	}
	public void setPrevCommCustomer(String prevCommCustomer) {
		this.prevCommCustomer = prevCommCustomer;
	}
	public String getGroupPackageInstanceId() {
		return groupPackageInstanceId;
	}
	public void setGroupPackageInstanceId(String groupPackageInstanceId) {
		this.groupPackageInstanceId = groupPackageInstanceId;
	}
	public String getVesselType() {
		return vesselType;
	}
	public void setVesselType(String vesselType) {
		this.vesselType = vesselType;
	}
	public String getAircraftClass() {
		return aircraftClass;
	}
	public void setAircraftClass(String aircraftClass) {
		this.aircraftClass = aircraftClass;
	}
	public String getAircraftManufacturer() {
		return aircraftManufacturer;
	}
	public void setAircraftManufacturer(String aircraftManufacturer) {
		this.aircraftManufacturer = aircraftManufacturer;
	}
	public String getTailNumber() {
		return tailNumber;
	}
	public void setTailNumber(String tailNumber) {
		this.tailNumber = tailNumber;
	}
	public String getCountryOfRegistration() {
		return countryOfRegistration;
	}
	public void setCountryOfRegistration(String countryOfRegistration) {
		this.countryOfRegistration = countryOfRegistration;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}


	public String getRatePlanId() {
		return ratePlanId;
	}
	public void setRatePlanId(String ratePlanId) {
		this.ratePlanId = ratePlanId;
	}
	public boolean isRatePlanChangeInd() {
		return ratePlanChangeInd;
	}
	public void setRatePlanChangeInd(boolean ratePlanChangeInd) {
		this.ratePlanChangeInd = ratePlanChangeInd;
	}
	public String getSuffix() {
		return suffix;
	}
	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}
	public String getSalesOrg() {
		return salesOrg;
	}
	public void setSalesOrg(String salesOrg) {
		this.salesOrg = salesOrg;
	}
	public String getSourceSyatem() {
		return sourceSyatem;
	}
	public void setSourceSyatem(String sourceSyatem) {
		this.sourceSyatem = sourceSyatem;
	}
	@Override
	public String toString() {
		return "ServiceOrder [id=" + id + ", msisdn=" + msisdn + ", industryCode=" + industryCode + ", profitCenter="
				+ profitCenter + ", requestId=" + requestId + ", productCode=" + productCode + ", satisfiedRuleName="
				+ satisfiedRuleName + ", isManualValidationRequired=" + isManualValidationRequired
				+ ", isManualSegmentationRequired=" + isManualSegmentationRequired + ", salesRegion=" + salesRegion
				+ ", salesRegionCode=" + salesRegionCode + ", dpName=" + dpName + ", billingProfileCode="
				+ billingProfileCode + ", arAccountCode=" + arAccountCode + ", prevBusinessUnit=" + prevBusinessUnit
				+ ", prevCommericialMarket=" + prevCommericialMarket + ", prevRuleId=" + prevRuleId
				+ ", grpPkgInstance=" + grpPkgInstance + ", wholeSaleCust=" + wholeSaleCust + ", castOrgName="
				+ castOrgName + ", castVerticalMarket=" + castVerticalMarket + ", createdBy=" + createdBy
				+ ", updatedBy=" + updatedBy + ", createdTime=" + createdTime + ", updatedTime=" + updatedTime
				+ ", dpId=" + dpId + ", businessUnit=" + businessUnit + ", commVerticalMarket=" + commVerticalMarket
				+ ", scapId=" + scapId + ", product=" + product + ", subscriber=" + subscriber + ", ratePlan="
				+ ratePlan + ", verticalMarket=" + verticalMarket + ", simcardId=" + simcardId + ", countryName="
				+ countryName + ", marketSector=" + marketSector + ", imoNumber=" + imoNumber + ", vesselName="
				+ vesselName + ", typeOfVessel=" + typeOfVessel + ", aircraftModel=" + aircraftModel + ", aeroType="
				+ aeroType + ", tailNo=" + tailNo + ", callSign=" + callSign + ", effectiveDate=" + effectiveDate
				+ ", mmsi=" + mmsi + ", idType=" + idType + ", organisaionId=" + organisaionId + ", organisationName="
				+ organisationName + ", verticalMarketKey=" + verticalMarketKey + ", customerKey=" + customerKey
				+ ", customerName=" + customerName + ", companyId=" + companyId + ", companyName=" + companyName
				+ ", hardwareId=" + hardwareId + ", imsiNumber=" + imsiNumber + ", corporateName=" + corporateName
				+ ", prevCommCustomer=" + prevCommCustomer + ", groupPackageInstanceId=" + groupPackageInstanceId
				+ ", vesselType=" + vesselType + ", aircraftClass=" + aircraftClass + ", aircraftManufacturer="
				+ aircraftManufacturer + ", tailNumber=" + tailNumber + ", countryOfRegistration="
				+ countryOfRegistration + ", status=" + status + ", ratePlanId=" + ratePlanId + ", ratePlanChangeInd="
				+ ratePlanChangeInd + ", suffix=" + suffix + ", salesOrg=" + salesOrg + ", sourceSyatem=" + sourceSyatem
				+ "]";
	}

}