package com.inmarsat.profitcentre;


import java.util.Map;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceOrderUtil implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private Map<String, String> indCdBuMap;
	private Map<String, String> proftCtMap;
    private	Map<String, String> ratePlanBuMap;
    private	Map<String, String> salesRegCdBuMap;
	private Map<String, String> customerBuMap;
	private Map<String, String> compIdBuMap;
	private Map<String, String> ruleConfigMap;
	
	public Map<String, String> getIndCdBuMap() {
		return indCdBuMap;
	}
	public void setIndCdBuMap(Map<String, String> indCdBuMap) {
		this.indCdBuMap = indCdBuMap;
	}
	public Map<String, String> getProftCtMap() {
		return proftCtMap;
	}
	public void setProftCtMap(Map<String, String> proftCtMap) {
		this.proftCtMap = proftCtMap;
	}
	public Map<String, String> getRatePlanBuMap() {
		return ratePlanBuMap;
	}
	public void setRatePlanBuMap(Map<String, String> ratePlanBuMap) {
		this.ratePlanBuMap = ratePlanBuMap;
	}
	public Map<String, String> getSalesRegCdBuMap() {
		return salesRegCdBuMap;
	}
	public void setSalesRegCdBuMap(Map<String, String> salesRegCdBuMap) {
		this.salesRegCdBuMap = salesRegCdBuMap;
	}
	public Map<String, String> getCustomerBuMap() {
		return customerBuMap;
	}
	public void setCustomerBuMap(Map<String, String> customerBuMap) {
		this.customerBuMap = customerBuMap;
	}
	public Map<String, String> getCompIdBuMap() {
		return compIdBuMap;
	}
	public void setCompIdBuMap(Map<String, String> compIdBuMap) {
		this.compIdBuMap = compIdBuMap;
	}
	
	public Map<String, String> getRuleConfigMap() {
		return ruleConfigMap;
	}
	public void setRuleConfigMap(Map<String, String> ruleConfigMap) {
		this.ruleConfigMap = ruleConfigMap;
	}
	@Override
	public String toString() {
		return "ServiceOrderUtil [indCdBuMap=" + indCdBuMap + ", proftCtMap=" + proftCtMap + ", ratePlanBuMap="
				+ ratePlanBuMap + ", salesRegCdBuMap=" + salesRegCdBuMap + ", customerBuMap=" + customerBuMap
				+ ", compIdBuMap=" + compIdBuMap + ", ruleConfigMap=" + ruleConfigMap + "]";
	}
	
	
	
	
	


   

}