 package com.inmarsat.profitcentre;

import org.jbpm.workflow.instance.WorkflowProcessInstance;
import java.util.HashMap;


global java.util.Map indCdBuMap;
global java.util.Map proftCtMap;
global java.util.Map ratePlanBuMap;
global java.util.Map salesRegCodeBuMap;
global java.util.Map customerBuMap;
global java.util.Map imoIndBUMap;
global java.util.Map customerSegBUMap;



rule "Test"

ruleflow-group "profitCentre"
when
processInstance : WorkflowProcessInstance()

then

		
        ServiceOrder order=(ServiceOrder)processInstance.getVariable("serviceOrder");
        ServiceOrderUtil util=(ServiceOrderUtil)processInstance.getVariable("serviceOrderUtil");
       //  ServiceOrder order=new  ServiceOrder();
        insert(order);
       
end



rule "Rule 1 - New service activation order for specific DPs (DP id 1020 & 3033)DP applicable - DP id 1020"  
ruleflow-group "profitCentre"
	when 
		$so : ServiceOrder( 
		satisfiedRuleName == null,
		salesRegionCode != null, 
		profitCenter == null, 
		dpId != null, 
		dpId == "1020"
		 )
		 $util:ServiceOrderUtil(
		     salesRegCdBuMap!=null,
		   proftCtMap != null,
		   ruleConfigMap != null, ruleConfigMap.get("Rule 1 - New service activation order for specific DPs (DP id 1020 & 3033)DP applicable - DP id 1020") == "true"
		 )

		 
	then
	    
	    salesRegCodeBuMap=$util.getSalesRegCdBuMap();
	    proftCtMap=$util.getProftCtMap();
		$so.setBusinessUnit((String)salesRegCodeBuMap.get($so.getSalesRegionCode()));
		$so.setProfitCenter((String)proftCtMap.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());

		update($so);
end

rule "Rule 1 - New service activation order for specific DPs (DP id 1020 & 3033)DP applicable - DP id 3033" 
ruleflow-group "profitCentre"
	when 
			$so : ServiceOrder( satisfiedRuleName == null, 
			profitCenter == null,
			dpId != null, 
			dpId == "3033", 
			ratePlanChangeInd == false )
			$util:ServiceOrderUtil(
                 proftCtMap!=null,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 1 - New service activation order for specific DPs (DP id 1020 & 3033)DP applicable - DP id 3033")=="true"
             )

	then

		proftCtMap=$util.getProftCtMap();
		$so.setBusinessUnit("Maritime");
		$so.setProfitCenter((String)proftCtMap.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());

		update($so);
end

rule "Rule 3 - Adding a bespoke rate plan as part of activation service order" 
	ruleflow-group "profitCentre"
	when 
			$util:ServiceOrderUtil(
                 ratePlanBuMap!=null, rtPlanBuMap : ratePlanBuMap,
                 proftCtMap != null,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 3 - Adding a bespoke rate plan as part of activation service order")=="true"
             )
			$so : ServiceOrder( satisfiedRuleName == null, 
			industryCode != null, 
			profitCenter == null, 
			dpId != null, dpId not in ("3033", "1020"),
			ratePlanId != null,
		    rtPlanId : ratePlanId, 
			industryCd : industryCode,
			rtPlanBuMap.get(rtPlanId+","+industryCd) != null)
			

	then

		proftCtMap=$util.getProftCtMap();
		$so.setBusinessUnit((String)rtPlanBuMap.get(rtPlanId+","+industryCd));
		$so.setProfitCenter((String)proftCtMap.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end

rule "Rule 4 - Activation Service order belonging to specific Govt. service providers and industry code" 
	ruleflow-group "profitCentre"
	when 
		    $util : ServiceOrderUtil(
                 customerBuMap!=null, custBuMap : customerBuMap,
                 proftCtMap != null,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 4 - Activation Service order belonging to specific Govt. service providers and industry code")=="true"
                 )
		    $so : ServiceOrder( 
		    satisfiedRuleName == null, 
		    industryCode != null, 
		    profitCenter == null, 
		    dpId != null, 
		    dpId not in ("3033", "1020"),
		    custBuMap.get(dpId+","+industryCode) != null
		  )
		    

	then

		proftCtMap=$util.getProftCtMap();
		$so.setBusinessUnit((String)custBuMap.get($so.getDpId()+","+$so.getIndustryCode()));
		$so.setProfitCenter((String)proftCtMap.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end

rule "Rule 5 - Activation Service Order having industry codes for Govt. BU and Maritime services - Maritime" 
	ruleflow-group "profitCentre"
	when
		$util : ServiceOrderUtil(
				 imoIndBUMap!=null, imoIndBUMapN : imoIndBUMap,
				 proftCtMap != null, proftCtMapN : proftCtMap,
				 ruleConfigMap != null, ruleConfigMap.get("Rule 5 - Activation Service Order having industry codes for Govt. BU and Maritime services - Maritime")=="true"
			)
		$so : ServiceOrder( satisfiedRuleName == null,
		productCode != null, productCode == "FLET",
		imoNumber!=null,
		imoIndBUMapN.get(imoNumber) !=  null,
		profitCenter == null, dpId != null,
		dpId not in ("3033", "1020"))
		
	then
		$so.setVerticalMarket(((String)imoIndBUMapN.get($so.getImoNumber())).split(",")[0]);
		$so.setBusinessUnit(((String)imoIndBUMapN.get($so.getImoNumber())).split(",")[1]);
		$so.setProfitCenter((String)proftCtMapN.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end

rule "Rule 5 - Activation Service Order having industry codes for Govt. BU and Maritime services - USA" 
	ruleflow-group "profitCentre"
	when 
		$util : ServiceOrderUtil(
                 indCdBuMap!=null, indCdBuMapN : indCdBuMap, 
                 proftCtMap != null, proftCtMapN : proftCtMap,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 5 - Activation Service Order having industry codes for Govt. BU and Maritime services - USA")=="true"
             )
		$so : ServiceOrder( satisfiedRuleName == null, 
		productCode != null, productCode == "FLET", 
		indCdBuMapN.get(industryCode) == "Global/US Govt.",
		countryName != null, countryName == "US", 
		profitCenter == null, dpId != null,
		dpId not in ("3033", "1020"))

	then

		$so.setBusinessUnit("US Government");
		$so.setProfitCenter((String)proftCtMapN.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end

rule "Rule 5 - Activation Service Order having industry codes for Govt. BU and Maritime services-Non USA" 
	ruleflow-group "profitCentre"
	when 
		$util : ServiceOrderUtil(
                 indCdBuMap!=null, indCdBuMapN : indCdBuMap, 
                 proftCtMap != null, proftCtMapN : proftCtMap,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 5 - Activation Service Order having industry codes for Govt. BU and Maritime services-Non USA")=="true"
             )
		$so : ServiceOrder( satisfiedRuleName == null, 
		productCode != null, productCode == "FLET", 
		indCdBuMapN.get(industryCode) == "Global/US Govt.",
		countryName != null, countryName != "US", 
		profitCenter == null, dpId != null,
		dpId not in ("3033", "1020"))

	then

		$so.setBusinessUnit("Global Government");
		$so.setProfitCenter((String)proftCtMapN.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end


rule "Rule 6 - Activation Service Order having industry codes for Govt. BU and Aviation services - USA"
	ruleflow-group "profitCentre"
	when 
		$util : ServiceOrderUtil(
                 indCdBuMap!=null, indCdBuMapN : indCdBuMap, 
                 proftCtMap != null, proftCtMapN : proftCtMap,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 6 - Activation Service Order having industry codes for Govt. BU and Aviation services - USA")=="true"
             )
		$so : ServiceOrder( satisfiedRuleName == null, 
		productCode != null, productCode == "SWFT", 
		indCdBuMapN.get(industryCode) == "Global/US Govt.",
		countryName != null, countryName == "US", 
		profitCenter == null, dpId != null,
		dpId not in ("3033", "1020"))

	then

		$so.setBusinessUnit("US Government");
		$so.setProfitCenter((String)proftCtMapN.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end

rule "Rule 6 - Activation Service Order having industry codes for Govt. BU and Aviation services-Non USA"
	ruleflow-group "profitCentre"
	when 
		$util : ServiceOrderUtil(
                 indCdBuMap!=null, indCdBuMapN : indCdBuMap, 
                 proftCtMap != null, proftCtMapN : proftCtMap,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 6 - Activation Service Order having industry codes for Govt. BU and Aviation services-Non USA")=="true"
             )
		$so : ServiceOrder( satisfiedRuleName == null, 
		productCode != null, productCode == "SWFT", 
		indCdBuMapN.get(industryCode) == "Global/US Govt.",
		countryName != null, countryName != "US", 
		profitCenter == null, dpId != null,
		dpId not in ("3033", "1020"))

	then

		$so.setBusinessUnit("Global Government");
		$so.setProfitCenter((String)proftCtMapN.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end

rule "Rule 7 - Activation Service Order having industry codes for Aviation and product is Swift Broadband (SB)"
	ruleflow-group "profitCentre"
	when 
		$util : ServiceOrderUtil(
                 indCdBuMap!=null, indCdBuMapN : indCdBuMap, 
                 proftCtMap != null, proftCtMapN : proftCtMap,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 7 - Activation Service Order having industry codes for Aviation and product is Swift Broadband (SB)")=="true"
             )
		$so : ServiceOrder( satisfiedRuleName == null, 
		productCode != null, productCode == "SWFT", 
		indCdBuMapN.get(industryCode) == "Aviation",
		profitCenter == null, dpId != null,
		dpId not in ("3033", "1020"))

	then

		$so.setBusinessUnit("Aviation");
		$so.setProfitCenter((String)proftCtMapN.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end

rule "Rule 8 - Activation Service Order having industry codes for respective business units"
	ruleflow-group "profitCentre"
	when 
		$util : ServiceOrderUtil(
                 indCdBuMap!=null, indCdBuMapN : indCdBuMap, 
                 proftCtMap != null, proftCtMapN : proftCtMap,
                 ratePlanBuMap!=null, rtPlanBuMap : ratePlanBuMap,
                 ruleConfigMap != null, ruleConfigMap.get("Rule 8 - Activation Service Order having industry codes for respective business units")=="true"
             )
		$so : ServiceOrder( satisfiedRuleName == null, 
		industryCode != null, 
		profitCenter == null, 
		dpId != null, dpId not in ("3033", "1020","1090"),
		industryCode not in ("Telecommunications Service Provider", "Professional Services", "Construction"), 
		indCdBuMapN.get(industryCode) != null,
		(productCode == null || (productCode not in ("SWFT","FLET") && indCdBuMapN.get(industryCode) != "Global/US Govt.")),
		rtPlanBuMap.get(ratePlanId+","+industryCode) == null)

	then

		$so.setBusinessUnit((String)indCdBuMapN.get($so.getIndustryCode()));
		$so.setProfitCenter((String)proftCtMapN.get($so.getBusinessUnit()+","+$so.getDpId()));
		$so.setSatisfiedRuleName(drools.getRule().getName());
		$so.setManualValidationRequired(true);
		update($so);
end


    
    
