package com.inmarsat.profitcentre;

import com.inmarsat.profitcentre.ESASRequest;
import com.inmarsat.profitcentre.ESASUtil;
import org.jbpm.workflow.instance.WorkflowProcessInstance;
global java.util.Map compIdBu;
global java.util.Map esasProdIndBuMap;
global java.util.Map esasProdBuCdBuMap;
global java.util.Map esasCntryOfRegBuMap;
global java.util.Map proftCt;



rule "Rule 1 - Terminal belonging to specific company ids in CAST- Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null,
			   profitCentre == null, dpId != null, companyId != null)
		$util : ESASUtil(
		        compIdBUMap != null,
		        proftCtMap != null)
		//processInstance : WorkflowProcessInstance()
	then
	
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
		compIdBu=$util.getCompIdBUMap();
		proftCt=$util.getProftCtMap();
		$erq.setBusinessUnitPC((String)compIdBu.get($erq.getCompanyId()));
		$erq.setProfitCentre((String)proftCt.get($erq.getBusinessUnitPC()+","+$erq.getDpId()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "company id: " + $erq.getCompanyId() );
		System.out.println( "DP id: " + $erq.getDpId() );
		System.out.println( "profit center: " + $erq.getProfitCentre() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 2 - Terminal belonging to Government industry code USA-Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
			   dpId != null, catCode != null, businessUnit != null , countryOfRegistration != null, countryOfRegistration == "USA",
			   eIndCd : catCode, eBuName : businessUnit, country : countryOfRegistration)
		$util : ESASUtil(
		        proftCtMap != null,
		        esasCntryOfRegBu != null
		        )
		//processInstance : WorkflowProcessInstance()
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
	 	proftCt=$util.getProftCtMap();
	 	esasCntryOfRegBuMap=$util.getEsasCntryOfRegBu();
		$erq.setBusinessUnitPC((String) esasCntryOfRegBuMap.get(country+","+eIndCd+","+eBuName));
		$erq.setProfitCentre((String)proftCt.get($erq.getBusinessUnitPC()+","+$erq.getDpId()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "DP id: " + $erq.getDpId() );
		System.out.println( "countryOfRegistration: " + $erq.getCountryOfRegistration() );
		System.out.println( "catCode: " + $erq.getCatCode() );
		System.out.println( "profit center: " + $erq.getProfitCentre() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 2 - Terminal belonging to Government industry code Non-USA-Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
			   dpId != null, catCode != null, businessUnit != null , countryOfRegistration != null, 
			   countryOfRegistration != "USA", eIndCd : catCode, eBuName : businessUnit)
		$util : ESASUtil(
		        proftCtMap != null, 
		        esasCntryOfRegBu != null 
		       )
		//processInstance : WorkflowProcessInstance()
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
		proftCt=$util.getProftCtMap();
	 	esasCntryOfRegBuMap=$util.getEsasCntryOfRegBu();
		$erq.setBusinessUnitPC((String) esasCntryOfRegBuMap.get("Non-USA"+","+eIndCd+","+eBuName));
		$erq.setProfitCentre((String)proftCt.get($erq.getBusinessUnitPC()+","+$erq.getDpId()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "DP id: " + $erq.getDpId() );
		System.out.println( "countryOfRegistration: " + $erq.getCountryOfRegistration() );
		System.out.println( "catCode: " + $erq.getCatCode() );
		System.out.println( "profit center: " + $erq.getProfitCentre() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 3 - Segmentation for Classic Aero Terminals- Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
			   dpId != null, productCode != null, catCode != null)
		$util : ESASUtil(
		        proftCtMap != null,
		        esasProdIndBu != null
		        )
		//processInstance : WorkflowProcessInstance()
		
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
		proftCt=$util.getProftCtMap();
	 	esasProdIndBuMap=$util.getEsasProdIndBu();
		$erq.setBusinessUnitPC((String)esasProdIndBuMap.get($erq.getProductCode()+","+$erq.getCatCode()));
		$erq.setProfitCentre((String)proftCt.get($erq.getBusinessUnitPC()+","+$erq.getDpId()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
		
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    //	retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "DP id: " + $erq.getDpId() );
		System.out.println( "ProductCode: " + $erq.getProductCode() );
		System.out.println( "catCode: " + $erq.getCatCode() );
		System.out.println( "profit center: " + $erq.getProfitCentre() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 4 - Terminal assigned to a product and old industry code - Classic Aero"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
		dpId != null, productCode != null, businessUnit != null)
		$util : ESASUtil(
		        proftCtMap != null,
		        esasProdBuCdBu != null
		        )
	//	processInstance : WorkflowProcessInstance()
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
		proftCt=$util.getProftCtMap();
	 	esasProdBuCdBuMap=$util.getEsasProdBuCdBu();
		$erq.setBusinessUnitPC((String)esasProdBuCdBuMap.get($erq.getProductCode()+","+$erq.getBusinessUnit()));
		$erq.setProfitCentre((String)proftCt.get($erq.getBusinessUnitPC()+","+$erq.getDpId()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    //	p.setVariable("esasRequest",$erq);
    //	update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "DP id: " + $erq.getDpId() );
		System.out.println( "profit center: " + $erq.getProfitCentre() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 1 - Terminal belonging to specific company ids in CAST- Non-Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null,
			   profitCentre == null, dpId == null, companyId != null)
		$util : ESASUtil(
		        compIdBUMap != null
		        )
		//processInstance : WorkflowProcessInstance()
	then
	
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
		compIdBu=$util.getCompIdBUMap();
		$erq.setBusinessUnitPC((String)compIdBu.get($erq.getCompanyId()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "company id: " + $erq.getCompanyId() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 2 - Terminal belonging to Government industry code USA-Non Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
			   dpId == null, catCode != null, businessUnit != null , countryOfRegistration != null, countryOfRegistration == "USA",
			   eIndCd : catCode, eBuName : businessUnit, country : countryOfRegistration)
		$util : ESASUtil(
		       esasCntryOfRegBu != null
		        )
		//processInstance : WorkflowProcessInstance()
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
	 	
	 	esasCntryOfRegBuMap=$util.getEsasCntryOfRegBu();
		$erq.setBusinessUnitPC((String) esasCntryOfRegBuMap.get(country+","+eIndCd+","+eBuName));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "countryOfRegistration: " + $erq.getCountryOfRegistration() );
		System.out.println( "catCode: " + $erq.getCatCode() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 2 - Terminal belonging to Government industry code Non-USA-Non -Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
			   dpId == null, catCode != null, businessUnit != null , countryOfRegistration != null, 
			   countryOfRegistration != "USA", eIndCd : catCode, eBuName : businessUnit)
		$util : ESASUtil(
		        esasCntryOfRegBu != null 
		       )
		//processInstance : WorkflowProcessInstance()
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
		
	 	esasCntryOfRegBuMap=$util.getEsasCntryOfRegBu();
		$erq.setBusinessUnitPC((String) esasCntryOfRegBuMap.get("Non-USA"+","+eIndCd+","+eBuName));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "countryOfRegistration: " + $erq.getCountryOfRegistration() );
		System.out.println( "catCode: " + $erq.getCatCode() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule "Rule 3 - Segmentation for Classic Aero Terminals- Non Classic Aero"
ruleflow-group "derive_profitcentre"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
			   dpId == null, productCode != null, catCode != null)
		$util : ESASUtil(
		        esasProdIndBu != null
		        )
		//processInstance : WorkflowProcessInstance()
		
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
		
	 	esasProdIndBuMap=$util.getEsasProdIndBu();
		$erq.setBusinessUnitPC((String)esasProdIndBuMap.get($erq.getProductCode()+","+$erq.getCatCode()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
		
    	//p.setVariable("esasRequest",$erq);
    	//update(p);
    //	retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
		System.out.println( "ProductCode: " + $erq.getProductCode() );
		System.out.println( "catCode: " + $erq.getCatCode() );
		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end

rule  "Rule 4 - Terminal assigned to a product and old industry code - Non - Classic Aero"
	when 
		$erq : ESASRequest( satisfiedRuleName == null, profitCentre == null, 
		dpId == null, productCode != null, businessUnit != null)
		$util : ESASUtil(
		        esasProdBuCdBu != null
		        )
	//	processInstance : WorkflowProcessInstance()
	then
	//WorkflowProcessInstance p = (WorkflowProcessInstance)kcontext.getKieRuntime().getProcessInstance(processInstance.getId());
	 	esasProdBuCdBuMap=$util.getEsasProdBuCdBu();
		$erq.setBusinessUnitPC((String)esasProdBuCdBuMap.get($erq.getProductCode()+","+$erq.getBusinessUnit()));
		$erq.setSatisfiedRuleName(drools.getRule().getName());
		update($erq);
    //	p.setVariable("esasRequest",$erq);
    //	update(p);
    	//retract(p);
		System.out.println( "-------------****Rule Execution Details****------------" );
		System.out.println( "business unit: " + $erq.getBusinessUnit() );
		System.out.println( "business unitPC: " + $erq.getBusinessUnitPC() );
 		System.out.println( "rule name: " + $erq.getSatisfiedRuleName() );
end
