package com.inmarsat.profitcentre;

import java.util.Map;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ESASUtil implements java.io.Serializable {
 
    static final long serialVersionUID = 1L;

   
        
    private Map<String, String> compIdBUMap;
	private Map<String, String> esasProdIndBu;
	private Map<String,String> esasProdBuCdBu ;
	private Map<String,String> esasCntryOfRegBu ;
	private Map<String, String> proftCtMap;
	public Map<String, String> getCompIdBUMap() {
		return compIdBUMap;
	}
	public void setCompIdBUMap(Map<String, String> compIdBUMap) {
		this.compIdBUMap = compIdBUMap;
	}
	public Map<String, String> getEsasProdIndBu() {
		return esasProdIndBu;
	}
	public void setEsasProdIndBu(Map<String, String> esasProdIndBu) {
		this.esasProdIndBu = esasProdIndBu;
	}
	public Map<String, String> getEsasProdBuCdBu() {
		return esasProdBuCdBu;
	}
	public void setEsasProdBuCdBu(Map<String, String> esasProdBuCdBu) {
		this.esasProdBuCdBu = esasProdBuCdBu;
	}
	public Map<String, String> getEsasCntryOfRegBu() {
		return esasCntryOfRegBu;
	}
	public void setEsasCntryOfRegBu(Map<String, String> esasCntryOfRegBu) {
		this.esasCntryOfRegBu = esasCntryOfRegBu;
	}
	public Map<String, String> getProftCtMap() {
		return proftCtMap;
	}
	public void setProftCtMap(Map<String, String> proftCtMap) {
		this.proftCtMap = proftCtMap;
	}
	
   

}